### ISSUE TITLE
[1.19.2] Crash with "Controllable" mod

### ISSUE THREAD

**Issue by xhatz** [SolarMoonQAQ/Spyglass-of-Curios#7]
Hello, it is me again! First of all, thank you very much for the quick update for the config options to disable the models!

I am having a problem, when the mod "Controllable" is installed to play with a controller, with this mod installed as well, the game crashes on startup. The exact same problem happened with the other "Spyglass Improvement" mod. I was wondering if you could fix it if possible please!

Since it is happening on other spyglass mod as well, I don't know how hard it would be, so it is okay if you cannot really fix it, I can do without Controllable.

Thank you again!

**Comment by SolarMoonQAQ** [comment]
you mean MrCrayFish's Controllable mod? I will check the issue. But I don’t have a controller or anything like that for debugging, so I’m not sure if it will work properly after the changes. I’ll give it a try!

**Comment by SolarMoonQAQ** [comment]
> Hello, it is me again! First of all, thank you very much for the quick update for the config options to disable the models!
> 
> I am having a problem, when the mod "Controllable" is installed to play with a controller, with this mod installed as well, the game crashes on startup. The exact same problem happened with the other "Spyglass Improvement" mod. I was wondering if you could fix it if possible please!
> 
> Since it is happening on other spyglass mod as well, I don't know how hard it would be, so it is okay if you cannot really fix it, I can do without Controllable.
> 
> Thank you again!

[spyglassofcurios-forge-1.19.2-1.4.1.zip](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/13464166/spyglassofcurios-forge-1.19.2-1.4.1.zip)  
Try this version, if it works properly, please let me know, and then I will publish it on the mod website.

**Comment by xhatz** [comment]
I will try thank you! In the mean time, I have found another bug. I installed the mod on a forge 1.19.2 server but it crashes also on startup of the server :(

`        Forge: net.minecraftforge:43.3.5[14:38:06] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Spyglass of Curios (spyglassofcurios) has failed to load correctly
?7java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[fmlcore-1.19.2-43.3.5.jar%23306!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$24(ModLoader.java:208) ~[fmlcore-1.19.2-43.3.5.jar%23306!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:208) ~[fmlcore-1.19.2-43.3.5.jar%23306!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$14(ModLoader.java:185) ~[fmlcore-1.19.2-43.3.5.jar%23306!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:185) ~[fmlcore-1.19.2-43.3.5.jar%23306!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.19.2-43.3.5-universal.jar%23310!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23305!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}`

**Comment by xhatz** [comment]
I just tested the fix for Controllable mod, it works perfectly, thank you!

**Comment by SolarMoonQAQ** [comment]
> I just tested the fix for Controllable mod, it works perfectly, thank you!

[spyglassofcurios-forge-1.19.2-1.4.1.zip](https://github.com/SolarMoonQAQ/Spyglass-of-Curios/files/13464349/spyglassofcurios-forge-1.19.2-1.4.1.zip)
Try this one, it could work normally on server in theory.

**Comment by xhatz** [comment]
Now the server starts with no problems! Thank you so much for your work ❤️
